"""empty message

Revision ID: 0b39793ece44
Revises: 865167a5e4da
Create Date: 2018-03-04 14:05:06.656260

"""

# revision identifiers, used by Alembic.
revision = '0b39793ece44'
down_revision = '865167a5e4da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('gensim_doc', sa.String(length=6000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'gensim_doc')
    # ### end Alembic commands ###
