"""empty message

Revision ID: 206502397f22
Revises: 332c7666bb44
Create Date: 2018-02-22 16:36:22.938366

"""

# revision identifiers, used by Alembic.
revision = '206502397f22'
down_revision = '332c7666bb44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('image_portrait', sa.Boolean(), nullable=True))
    op.add_column('staff', sa.Column('image_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'image_width')
    op.drop_column('staff', 'image_portrait')
    op.drop_column('staff', 'image_height')
    # ### end Alembic commands ###
