"""empty message

Revision ID: 2b209d8bd8a2
Revises: 367f9d74f83f
Create Date: 2018-04-01 01:22:56.928590

"""

# revision identifiers, used by Alembic.
revision = '2b209d8bd8a2'
down_revision = '367f9d74f83f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'app_user_email_key', 'app_user', type_='unique')
    op.drop_column('app_user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_unique_constraint(u'app_user_email_key', 'app_user', ['email'])
    # ### end Alembic commands ###
