"""empty message

Revision ID: 2dd14e0d6315
Revises: fcf71b6f267d
Create Date: 2018-02-10 19:22:34.252251

"""

# revision identifiers, used by Alembic.
revision = '2dd14e0d6315'
down_revision = 'fcf71b6f267d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
