"""empty message

Revision ID: 2df876d996c0
Revises: 6e92e3ac7a84
Create Date: 2018-02-21 22:38:13.217528

"""

# revision identifiers, used by Alembic.
revision = '2df876d996c0'
down_revision = '6e92e3ac7a84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('url_name', sa.String(length=400), nullable=True),
    sa.Column('count_subjects', sa.Integer(), nullable=True),
    sa.Column('count_staff', sa.Integer(), nullable=True),
    sa.Column('count_modules', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=4000), nullable=True),
    sa.Column('color_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
