"""empty message

Revision ID: 2fda867e709d
Revises: None
Create Date: 2018-02-10 04:30:42.116879

"""

# revision identifiers, used by Alembic.
revision = '2fda867e709d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
