"""empty message

Revision ID: 332c7666bb44
Revises: deb5f97f359c
Create Date: 2018-02-22 13:01:58.363886

"""

# revision identifiers, used by Alembic.
revision = '332c7666bb44'
down_revision = 'deb5f97f359c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
