"""empty message

Revision ID: 34f342ab44b9
Revises: 42af53cdc902
Create Date: 2018-02-11 02:29:20.329935

"""

# revision identifiers, used by Alembic.
revision = '34f342ab44b9'
down_revision = '42af53cdc902'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
