"""empty message

Revision ID: 3f2e180a9467
Revises: 2b209d8bd8a2
Create Date: 2018-04-01 01:23:24.771377

"""

# revision identifiers, used by Alembic.
revision = '3f2e180a9467'
down_revision = '2b209d8bd8a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
