"""empty message

Revision ID: 42af53cdc902
Revises: 64e7932f14f1
Create Date: 2018-02-11 02:03:56.304296

"""

# revision identifiers, used by Alembic.
revision = '42af53cdc902'
down_revision = '64e7932f14f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
