"""empty message

Revision ID: 495a88477b8c
Revises: 85b237bde7bd
Create Date: 2018-03-07 13:32:17.013324

"""

# revision identifiers, used by Alembic.
revision = '495a88477b8c'
down_revision = '85b237bde7bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth2_token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=48), nullable=False),
    sa.Column('refresh_token', sa.String(length=48), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('o_auth2_token')
    # ### end Alembic commands ###
