"""empty message

Revision ID: 4d5e818c4b6e
Revises: 206502397f22
Create Date: 2018-02-22 16:38:21.301337

"""

# revision identifiers, used by Alembic.
revision = '4d5e818c4b6e'
down_revision = '206502397f22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
