"""empty message

Revision ID: 615a1a23cfd8
Revises: 2df876d996c0
Create Date: 2018-02-21 22:38:29.121723

"""

# revision identifiers, used by Alembic.
revision = '615a1a23cfd8'
down_revision = '2df876d996c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
