"""empty message

Revision ID: 639571d2dd7f
Revises: 2fda867e709d
Create Date: 2018-02-10 05:34:58.985258

"""

# revision identifiers, used by Alembic.
revision = '639571d2dd7f'
down_revision = '2fda867e709d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
