"""empty message

Revision ID: 64e7932f14f1
Revises: 6ec811552a11
Create Date: 2018-02-10 19:37:59.173983

"""

# revision identifiers, used by Alembic.
revision = '64e7932f14f1'
down_revision = '6ec811552a11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
