"""empty message

Revision ID: 64eed531e8ab
Revises: b952f6b2d510
Create Date: 2018-03-15 23:19:01.877913

"""

# revision identifiers, used by Alembic.
revision = '64eed531e8ab'
down_revision = 'b952f6b2d510'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
