"""empty message

Revision ID: 6e92e3ac7a84
Revises: 89d7ef4f2cf9
Create Date: 2018-02-20 11:24:58.303323

"""

# revision identifiers, used by Alembic.
revision = '6e92e3ac7a84'
down_revision = '89d7ef4f2cf9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
