"""empty message

Revision ID: 85b237bde7bd
Revises: 0b39793ece44
Create Date: 2018-03-04 14:05:17.525889

"""

# revision identifiers, used by Alembic.
revision = '85b237bde7bd'
down_revision = '0b39793ece44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
