"""empty message

Revision ID: 865167a5e4da
Revises: b65d23fb2477
Create Date: 2018-02-23 01:24:29.651553

"""

# revision identifiers, used by Alembic.
revision = '865167a5e4da'
down_revision = 'b65d23fb2477'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
