"""empty message

Revision ID: 88c2b8a016fb
Revises: dd2b79639787
Create Date: 2018-03-07 19:10:48.906688

"""

# revision identifiers, used by Alembic.
revision = '88c2b8a016fb'
down_revision = 'dd2b79639787'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('count_logins', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'count_logins')
    # ### end Alembic commands ###
