"""empty message

Revision ID: 89d7ef4f2cf9
Revises: 34f342ab44b9
Create Date: 2018-02-20 11:17:48.401433

"""

# revision identifiers, used by Alembic.
revision = '89d7ef4f2cf9'
down_revision = '34f342ab44b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('gensim_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'module', ['gensim_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='unique')
    op.drop_column('module', 'gensim_id')
    # ### end Alembic commands ###
