"""empty message

Revision ID: b952f6b2d510
Revises: 88c2b8a016fb
Create Date: 2018-03-15 23:18:51.867530

"""

# revision identifiers, used by Alembic.
revision = 'b952f6b2d510'
down_revision = '88c2b8a016fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_joined')
    # ### end Alembic commands ###
