"""empty message

Revision ID: dd2b79639787
Revises: a88d2b9ff318
Create Date: 2018-03-07 15:30:05.831369

"""

# revision identifiers, used by Alembic.
revision = 'dd2b79639787'
down_revision = 'a88d2b9ff318'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
