"""empty message

Revision ID: deb5f97f359c
Revises: 615a1a23cfd8
Create Date: 2018-02-22 13:01:39.676428

"""

# revision identifiers, used by Alembic.
revision = 'deb5f97f359c'
down_revision = '615a1a23cfd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('first_name', sa.String(length=400), nullable=True),
    sa.Column('last_name', sa.String(length=400), nullable=True),
    sa.Column('short_title', sa.String(length=400), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('url_name', sa.String(length=4000), nullable=True),
    sa.Column('count_subjects', sa.Integer(), nullable=True),
    sa.Column('count_schools', sa.Integer(), nullable=True),
    sa.Column('count_modules', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=4000), nullable=True),
    sa.Column('color_code', sa.String(length=50), nullable=True),
    sa.Column('unknown_name', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'school', 'url_name',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=4000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'school', 'url_name',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.drop_table('staff')
    # ### end Alembic commands ###
