"""empty message

Revision ID: ee49eb375a52
Revises: 3f2e180a9467
Create Date: 2018-04-01 01:47:03.472931

"""

# revision identifiers, used by Alembic.
revision = 'ee49eb375a52'
down_revision = '3f2e180a9467'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('o_auth2_token', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('o_auth2_token', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
