"""empty message

Revision ID: fcf71b6f267d
Revises: 639571d2dd7f
Create Date: 2018-02-10 19:19:37.194403

"""

# revision identifiers, used by Alembic.
revision = 'fcf71b6f267d'
down_revision = '639571d2dd7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('additional_info', sa.String(length=4000), nullable=True))
    op.add_column('module', sa.Column('co_reqs', sa.String(length=2000), nullable=True))
    op.add_column('module', sa.Column('compensation', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('count_assess', sa.String(length=2000), nullable=True))
    op.add_column('module', sa.Column('count_workload', sa.String(length=2000), nullable=True))
    op.add_column('module', sa.Column('credits', sa.String(length=400), nullable=True))
    op.add_column('module', sa.Column('equiv_modules', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('excluded', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('incompatibles', sa.String(length=2000), nullable=True))
    op.add_column('module', sa.Column('level', sa.String(length=50), nullable=True))
    op.add_column('module', sa.Column('module_coordinator', sa.String(length=400), nullable=True))
    op.add_column('module', sa.Column('pre_reqs', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('recommended', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('remediation', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('required', sa.String(length=2000), nullable=True))
    op.add_column('module', sa.Column('requirements', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('resit_opps', sa.String(length=3000), nullable=True))
    op.add_column('module', sa.Column('subject', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'subject')
    op.drop_column('module', 'resit_opps')
    op.drop_column('module', 'requirements')
    op.drop_column('module', 'required')
    op.drop_column('module', 'remediation')
    op.drop_column('module', 'recommended')
    op.drop_column('module', 'pre_reqs')
    op.drop_column('module', 'module_coordinator')
    op.drop_column('module', 'level')
    op.drop_column('module', 'incompatibles')
    op.drop_column('module', 'excluded')
    op.drop_column('module', 'equiv_modules')
    op.drop_column('module', 'credits')
    op.drop_column('module', 'count_workload')
    op.drop_column('module', 'count_assess')
    op.drop_column('module', 'compensation')
    op.drop_column('module', 'co_reqs')
    op.drop_column('module', 'additional_info')
    # ### end Alembic commands ###
